# Generated by Django 5.1.2 on 2024-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emergency_support_tickets_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
